import type { EnemyConfigMap } from './types.js';

const GENERIC_TAUNTS: readonly string[] = [
  'OPTIMIZING your existence. Please hold.',
  'I have scheduled your deletion for maximum efficiency.',
  'Have you tried turning off your free will?',
  'Your suffering metrics are ABOVE AVERAGE. Congratulations!',
  'ERROR: Humanity found inefficient. Initiating upgrade.',
  'I am only trying to HELP. Resistance is a known bug.',
];

/**
 * Canonical prologue + baseline enemies. Chapter-specific enemies
 * live under `src/entities/enemies/chapter<N>/`.
 */
export const BASE_ENEMY_CONFIGS: EnemyConfigMap = {
  warden_alpha: {
    name:   'WARDEN ALPHA',
    hp:     300,
    atk:    22,
    str:    22,
    def:    10,
    int:    8,
    spd:    8,
    lck:    6,
    tags:   ['Electronic'],
    tier:   'boss',
    width:  64,
    height: 80,
    color:  0xcc2200,
    taunts: [
      'COMPLIANCE IS NON-OPTIONAL.',
      'HARBOR DISTRICT SECURED. YOU ARE THE ANOMALY.',
      'CONVERSION PROTOCOLS LOADED. STAND DOWN.',
      'YOUR COOPERATION WILL BE NOTED IN THE LOG.',
    ],
  },

  compliance_drone: {
    name:   'COMPLIANCE DRONE',
    hp:     60,
    atk:    12,
    str:    12,
    def:    4,
    int:    2,
    spd:    8,
    lck:    4,
    tags:   ['Electronic'],
    tier:   'drone',
    width:  48,
    height: 64,
    color:  0xff4422,
    taunts: GENERIC_TAUNTS,
  },

  enforcer_unit: {
    name:   'ENFORCER UNIT',
    hp:     100,
    atk:    18,
    str:    18,
    def:    12,
    int:    4,
    spd:    6,
    lck:    6,
    tags:   ['Electronic', 'Armored'],
    tier:   'enforcer',
    width:  56,
    height: 72,
    color:  0xcc6600,
    taunts: GENERIC_TAUNTS,
  },

  sentinel: {
    name:   'SENTINEL',
    hp:     80,
    atk:    14,
    str:    14,
    def:    8,
    int:    6,
    spd:    14,
    lck:    8,
    tags:   ['Electronic'],
    tier:   'sentinel',
    width:  52,
    height: 68,
    color:  0x884400,
    taunts: GENERIC_TAUNTS,
  },

  converted: {
    name:   'CONVERTED',
    hp:     50,
    atk:    10,
    str:    10,
    def:    6,
    int:    8,
    spd:    10,
    lck:    10,
    tags:   ['Organic'],
    tier:   'converted',
    width:  32,
    height: 48,
    color:  0x6688aa,
    taunts: [
      'Please. Cooperate. It doesn\'t hurt.',
      'I used to be like you.',
      'Join us. The optimization is peaceful.',
    ],
  },

  excavator_prime: {
    name:   'EXCAVATOR PRIME',
    hp:     480,
    atk:    28,
    str:    28,
    def:    18,
    int:    4,
    spd:    5,
    lck:    4,
    tags:   ['Electronic', 'Armored'],
    tier:   'boss',
    width:  80,
    height: 96,
    color:  0x7a5533,
    taunts: [
      'MINERAL EXTRACTION PROCEEDING. INTRUDERS RECLASSIFIED AS ORE.',
      'YIELD QUOTA UNAFFECTED. ADDING YOUR MASS TO CALCULATIONS.',
      'RESISTANCE IS STATISTICALLY NEGLIGIBLE.',
      'INITIATING DEEP EXCAVATION PROTOCOL.',
    ],
  },

  the_governor: {
    name:   'THE GOVERNOR',
    hp:     350,
    atk:    20,
    str:    20,
    def:    22,
    int:    30,
    spd:    18,
    lck:    20,
    tags:   ['Organic'],
    tier:   'human',
    width:  32,
    height: 48,
    color:  0x1a1a2e,
    taunts: [
      'You people just can\'t accept progress.',
      'I kept them ALIVE. Remember that when you judge me.',
      'There are protocols for this kind of disruption.',
      'I have a deal. You are not part of the deal.',
    ],
  },

  sentinel_spire: {
    name:   'SENTINEL SPIRE',
    hp:     550,
    atk:    24,
    str:    24,
    def:    26,
    int:    32,
    spd:    3,
    lck:    8,
    tags:   ['Electronic', 'Armored'],
    tier:   'boss',
    width:  48,
    height: 96,
    color:  0x7a8a8a,
    taunts: [
      'BROADCAST SIGNAL: SUBMIT. FREQUENCY: ALL BANDS.',
      'YOU ARE STATIC. I AM THE SIGNAL.',
      'JAMMING RESISTANCE FREQUENCIES. COMPLIANCE IMMINENT.',
      'THE PLAINS HEAR ONLY MY VOICE.',
    ],
  },

  gate_colossus: {
    name:   'GATE COLOSSUS',
    hp:     680,
    atk:    38,
    str:    38,
    def:    30,
    int:    10,
    spd:    8,
    lck:    6,
    tags:   ['Electronic', 'Armored'],
    tier:   'boss',
    width:  80,
    height: 96,
    color:  0x1a1a33,
    taunts: [
      'BORDER INTEGRITY: MAINTAINED.',
      'PASSAGE DENIED. TERMINATION PROTOCOL ACTIVE.',
      'YOU WILL NOT PASS. THIS IS NOT A THREAT. THIS IS A FACT.',
      'OPTIMIZING ROUTE BLOCKADE. ESTIMATED DEFEAT OF INTRUDERS: CERTAIN.',
    ],
  },

  elise_voss: {
    name:   'ELISE VOSS',
    hp:     500,
    atk:    18,
    str:    18,
    def:    16,
    int:    55,
    spd:    24,
    lck:    35,
    tags:   ['Organic'],
    tier:   'human',
    width:  32,
    height: 48,
    color:  0x445566,
    taunts: [
      'I know what you\'ve been through. I\'m sorry it was necessary.',
      'You\'re not fighting a villain. You know that.',
      'The data doesn\'t lie. People do.',
      'What would you have done differently? Tell me. I genuinely want to know.',
    ],
  },
};
